### ISSUE TITLE
session not stored?

### ISSUE THREAD

**Issue by tgarm** [gofiber/session#8]
I've tried use session to store some data. But it seems data are not stored among different requests. Is it implementation issue or usage issue?

A simple use case is:

    package main
    import (
        "github.com/gofiber/fiber"
        "github.com/gofiber/session"
        "github.com/gofiber/session/provider/sqlite3"
    )

    func main(){
        app := fiber.New()

        provider := sqlite3.New(sqlite3.Config{
            DBPath: "session.db",
            TableName: "session",
        })
        sessions := session.New(session.Config{
            Provider: provider,
        })

        app.Get("/get", func(c *fiber.Ctx) {
            store := sessions.Get(c)
            defer store.Save()
            id,ok := store.Get("id").(int)
            if ok {
                c.Send("id=",id)
                store.Set("id",id+1)
            }else{
                c.Send("id empty, in session:",store.ID())
                store.Set("id",1)
            }
        })

        app.Listen(8060)
    }

And when use browser to reload "http://url/get", I expect the **id** to be increment while session ID keeps the same.

Actual result is **id** always empty, and session ID keeps the same.

I also tried **redis** provider, the result is the same.

Am I use the API correctly? Or is there anything wrong with the implementation?

**Comment by Fenny** [comment]
If you try `id++` before calling `Set`, does that work?

**Comment by tgarm** [comment]
It seems the code never successfully read "id" from the session, although it always try to set "id=1" to the session.
I've changed the code after **store.Get** to this:

            if ok {
                c.Send("id=",id)
                id++
                store.Set("id",id)
            }else{
                c.Send("id empty, in session:",store.ID())
                store.Set("id",2)
            }

The result is still the same, like this:

> id empty, in session:97cd65b7-dd94-42e1-955c-c8dfaf4d8549

What's wrong with it?

**Comment by Fenny** [comment]
Do you have the same behaviour using the default provider? It could be a MySQL problem

**Comment by tgarm** [comment]
The provider is **sqlite3**.
It always keep the same behavior. For instance, when access http://url/get, the response is always like this(session id may be different):
`id empty, in session:9c03b735-88e8-4bba-b50e-884b14109a0c`

And in the **session.db**, there is a record with the same session id:
`sqlite> select * from session;
9c03b735-88e8-4bba-b50e-884b14109a0c|gaFEkYKjS2V5xAJpZKVWYWx1ZQE=|1593387204498416100|43200000000000`

**Comment by Fenny** [comment]
I can't seem to reproduce the same behaviour 😞 could you try to update to the latest Fiber & Session packages?

**Comment by thomasvvugt** [comment]
@tgarm May I ask the operating system with which you are using the `sqlite3` provider?

**Comment by tgarm** [comment]
Thank you for your reply.

It runs on `Ubuntu Server 18.04.4 LTS /amd64`, and the version of sqlite3 is: `3.22.0-1ubuntu0.4`
Version of Go is: `go1.14.4 linux/amd64`
I just upgraded go packages with `go get -u`, it shows these versions:
`go: github.com/gofiber/fiber upgrade => v1.12.3`
`go: github.com/mattn/go-sqlite3 upgrade => v1.14.0`
`go: github.com/gofiber/session upgrade => v1.2.3`

The problem keeps the same.

**Comment by fuadarradhi** [comment]
> The provider is **sqlite3**.
> It always keep the same behavior. For instance, when access http://url/get, the response is always like this(session id may be different):
> `id empty, in session:9c03b735-88e8-4bba-b50e-884b14109a0c`
> 
> And in the **session.db**, there is a record with the same session id:
> `sqlite> select * from session; 9c03b735-88e8-4bba-b50e-884b14109a0c|gaFEkYKjS2V5xAJpZKVWYWx1ZQE=|1593387204498416100|43200000000000`

you need to check `if ok` is return true, and value in session.db is changed (not session id)

**Comment by thomasvvugt** [comment]
Hi @fuadarradhi, thanks for your comment. 😊
Can you confirm this, @tgarm? Thanks!

**Comment by tgarm** [comment]
Thank you for your concern!

__ok__ is returned __false__.
As for the field values in __session.db__:

- Before first access, no row exists
- After first access, a row with the session __id__ is created
- After each following access, field __last_active__ increases while field __data__ and __expiration__ always keep the same value.

**Comment by Fenny** [comment]
@tgarm, could you try if this is fixed in https://github.com/gofiber/session/releases/tag/v1.2.4?

**Comment by tgarm** [comment]
I've upgraded session to 1.2.4 and the result is still the same:
nothing changed in sqlite database file __session.db__

One thing different: Sometimes, when quit and re-rerun the go code, the following error message shows:

```
2020/07/23 11:44:25 session error: session: sqlite3 index last_active already exists; provider: sqlite3;
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x88b135]

goroutine 1 [running]:
github.com/fasthttp/session/v2/providers/sqlite3.(*Provider).NeedGC(0x0, 0xc0000be160)
	<autogenerated>:1 +0x5
github.com/fasthttp/session/v2.(*Session).SetProvider(0xc00015e000, 0xae9020, 0x0, 0x1, 0x1)
	/home/simon/go/pkg/mod/github.com/fasthttp/session/v2@v2.2.0/session.go:64 +0x4a
github.com/gofiber/session.New(0xc0004d1ea8, 0x1, 0x1, 0x0)
	/home/simon/go/pkg/mod/github.com/gofiber/session@v1.2.4/session.go:148 +0x4e2
main.main()
	/home/simon/modtest/go/min.go:17 +0x18d
exit status 2
```

**Comment by Fenny** [comment]
I just released <https://github.com/gofiber/session/releases/tag/v1.2.5>, this contains a fasthttp session update. Sorry to ask again, but could you try this version?

**Comment by tgarm** [comment]
Finally, after trace into the library,  I found it's because session store does __NOT__ support type __int__.
It works after changed variable type to __string__, like:

```go
id,ok := store.Get("id").(string)
if ok {
    iid,err := strconv.Atoi(id)
    if err!=nil {
        fmt.Println(err)
    }
    store.Set("id",strconv.Itoa(iid+1))
```

@Fenny  Thank you for your concern and help.
Would you please update the README document to reflect this?

**Comment by thomasvvugt** [comment]
Hi @tgarm,
That's odd, because I have been playing with the session middleware as well and integers work just fine for me.
However, I've only been using the `redis` provider. I will test this behavior with SQLite3 some time soon.
I'll re-open the issue to confirm this behavior, thanks for your response! 🚀

**Comment by sxci** [comment]
github.com/gofiber/fiber v1.13.3
github.com/gofiber/session v1.2.5

still have the problem


add some testes on  source code, may be better.

**Comment by Fenny** [comment]
@sxci, we opened an issue about the `int` not being support on fasthttp's end. ( `int64` seems to work fine )
> add some testes on source code, may be better.
I personally maintain around 32 repo's in my spare time, giving back to the community by submitting PR's is highly appreciated 👍

**Comment by thomasvvugt** [comment]
Also, I would like to mention the issue at FastHTTP's repo; https://github.com/fasthttp/session/issues/29

**Comment by tgarm** [comment]
Just checked, __int64__ works.

**Comment by thomasvvugt** [comment]
I'll leave this issue open for now, once we get an update on fasthttp/session#29

**Comment by thomasvvugt** [comment]
I'm closing this issue, for clarification please see https://github.com/fasthttp/session/issues/29#issuecomment-672286113
